spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue?useUnicode=true&character=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
  type-aliases-package: cn.opm.vue_service_api.mapper

server:
  port: 8080
logging:
  level.com.mybatis: debug
  level.cn.opm.vue_server_api: debug